//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceConst() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceConst", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su solicitud de Aval ha sido radicada correctamente..
        /// </summary>
        internal static string ConstConfirmacionRegistroAval {
            get {
                return ResourceManager.GetString("ConstConfirmacionRegistroAval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su solicitud de Condonación ha sido radicada correctamente..
        /// </summary>
        internal static string ConstConfirmacionRegistroCondonacion {
            get {
                return ResourceManager.GetString("ConstConfirmacionRegistroCondonacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.wordprocessingml.document.
        /// </summary>
        internal static string ConstContentOpenxmlformats {
            get {
                return ResourceManager.GetString("ConstContentOpenxmlformats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/pdf.
        /// </summary>
        internal static string ConstContentPdf {
            get {
                return ResourceManager.GetString("ConstContentPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/msword.
        /// </summary>
        internal static string ConstContentWord {
            get {
                return ResourceManager.GetString("ConstContentWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialización.
        /// </summary>
        internal static string ConstEspecializacion {
            get {
                return ResourceManager.GetString("ConstEspecializacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .pdf.
        /// </summary>
        internal static string ConstExtPdf {
            get {
                return ResourceManager.GetString("ConstExtPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maestría.
        /// </summary>
        internal static string ConstMaestria {
            get {
                return ResourceManager.GetString("ConstMaestria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cumple con puntaje mínimo requerido.
        /// </summary>
        internal static string ConstNoPuntaje {
            get {
                return ResourceManager.GetString("ConstNoPuntaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted aún no ha radicado su solicitud de Aval..
        /// </summary>
        internal static string ConstNoRegistrado {
            get {
                return ResourceManager.GetString("ConstNoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted aún no ha radicado su solicitud de Condonación..
        /// </summary>
        internal static string ConstNoRegistradoCondonacion {
            get {
                return ResourceManager.GetString("ConstNoRegistradoCondonacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conv{0}\.
        /// </summary>
        internal static string ConstPathConvocatoria {
            get {
                return ResourceManager.GetString("ConstPathConvocatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~\Data\.
        /// </summary>
        internal static string ConstPathData {
            get {
                return ResourceManager.GetString("ConstPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primera Convocatoria de Gobierno Electrónico.
        /// </summary>
        internal static string ConstPrimeraConvocatoria {
            get {
                return ResourceManager.GetString("ConstPrimeraConvocatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segunda Convocatoria de Gobierno Electrónico.
        /// </summary>
        internal static string ConstSegundaConvocatoria {
            get {
                return ResourceManager.GetString("ConstSegundaConvocatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALTA REGISTRAR.
        /// </summary>
        internal static string ConstSinEstado {
            get {
                return ResourceManager.GetString("ConstSinEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumple con puntaje mínimo requerido.
        /// </summary>
        internal static string ConstSiPuntaje {
            get {
                return ResourceManager.GetString("ConstSiPuntaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PuntajeInscritos.xlsx.
        /// </summary>
        internal static string FilePuntajeInscritos {
            get {
                return ResourceManager.GetString("FilePuntajeInscritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistroInscritos.xlsx.
        /// </summary>
        internal static string FileRegistroInscritos {
            get {
                return ResourceManager.GetString("FileRegistroInscritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistroInscritosCond.xlsx.
        /// </summary>
        internal static string FileRegistroInscritosCond {
            get {
                return ResourceManager.GetString("FileRegistroInscritosCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistroInscritosHistorico.xlsx.
        /// </summary>
        internal static string FileRegistroInscritosHistorico {
            get {
                return ResourceManager.GetString("FileRegistroInscritosHistorico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anexo 11 Modelo de Autorización para Uso Promoción y Divulgación del Video PCGE.docx.
        /// </summary>
        internal static string File_8809_Anexo11 {
            get {
                return ResourceManager.GetString("File_8809_Anexo11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9084_Anexo 11 Modelo de Autorización para Uso Promoción y Divulgación del Video SCGE.docx.
        /// </summary>
        internal static string File_9084_Anexo11 {
            get {
                return ResourceManager.GetString("File_9084_Anexo11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Plantillas/Anexos/.
        /// </summary>
        internal static string PathAnexos {
            get {
                return ResourceManager.GetString("PathAnexos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlUsers.xml.
        /// </summary>
        internal static string PathFileUsers {
            get {
                return ResourceManager.GetString("PathFileUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Plantillas/.
        /// </summary>
        internal static string PathPlantillas {
            get {
                return ResourceManager.GetString("PathPlantillas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Plantillas/ReqOpcEsp.html.
        /// </summary>
        internal static string PathReqOpcEsp {
            get {
                return ResourceManager.GetString("PathReqOpcEsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Plantillas/ReqOpcMaestria.html.
        /// </summary>
        internal static string PathReqOpcMaestria {
            get {
                return ResourceManager.GetString("PathReqOpcMaestria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Styles/StyleEspecializacion.css.
        /// </summary>
        internal static string PathStyleEspecializacion {
            get {
                return ResourceManager.GetString("PathStyleEspecializacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Styles/StyleMaestria.css.
        /// </summary>
        internal static string PathStyleMaestria {
            get {
                return ResourceManager.GetString("PathStyleMaestria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/agt_stop-32.png.
        /// </summary>
        internal static string UrlImgStop {
            get {
                return ResourceManager.GetString("UrlImgStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/agt_action_success-32.png.
        /// </summary>
        internal static string UrlImgSuccess {
            get {
                return ResourceManager.GetString("UrlImgSuccess", resourceCulture);
            }
        }
    }
}
